language: python
matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: 3.3
    env: TOXENV=py33
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 2.7
    env: TOXENV=py27-django4
  - python: 2.7
    env: TOXENV=py27-django5
  - python: 3.3
    env: TOXENV=py33-django5
  - python: 2.7
    env: TOXENV=py27-django6
  - python: 3.3
    env: TOXENV=py33-django6
  - python: 2.7
    env: TOXENV=py27-django7
  - python: 3.3
    env: TOXENV=py33-django7
  - python: 3.4
    env: TOXENV=py34-django7
  - python: 2.7
    env: TOXENV=py27-django8
  - python: 3.3
    env: TOXENV=py33-django8
  - python: 3.4
    env: TOXENV=py34-django8
  - python: 3.5
    env: TOXENV=py35-django8
  - python: 2.7
    env: TOXENV=py27-django9
  - python: 3.4
    env: TOXENV=py34-django9
  - python: 3.5
    env: TOXENV=py35-django9
  - python: 2.7
    env: TOXENV=py27-django10
  - python: 3.4
    env: TOXENV=py34-django10
  - python: 3.5
    env: TOXENV=py35-django10
  - python: 2.7
    env: TOXENV=py27-django11
  - python: 3.4
    env: TOXENV=py34-django11
  - python: 3.5
    env: TOXENV=py35-django11
  - python: 3.6
    env: TOXENV=py36-django11
install:
- pip install tox
script:
- tox -e $TOXENV

